import streamlit as st
import google.generativeai as genai
from PIL import Image
import pandas as pd
from datetime import datetime
import io
import re

# --- 1. CONFIGURATION & API ---
MY_API_KEY = "MY_API_KEY = st.secrets["GEMINI_API_KEY"]" 
genai.configure(api_key=MY_API_KEY)

# --- 2. LOGIN SYSTEM (Simple & Effective) ---
def login():
    st.sidebar.title("🔐 User Access")
    if 'logged_in' not in st.session_state:
        st.session_state.logged_in = False

    if not st.session_state.logged_in:
        user = st.sidebar.text_input("Username")
        pw = st.sidebar.text_input("Password", type="password")
        if st.sidebar.button("Login"):
            if user == "admin" and pw == "1234": # Startup ke liye yahan username/pw set karein
                st.session_state.logged_in = True
                st.rerun()
            else:
                st.sidebar.error("Galat details bhai!")
        return False
    else:
        if st.sidebar.button("Logout"):
            st.session_state.logged_in = False
            st.rerun()
        return True

# --- 3. MAIN APP ---
if login():
    st.title("🚀 AI Digital Accountant Pro")
    st.info("Status: Startup Mode Active | User: Admin")

    uploaded_file = st.file_uploader("Bill ki photo upload karein...", type=["jpg", "jpeg", "png"])

    if uploaded_file:
        col1, col2 = st.columns(2)
        img = Image.open(uploaded_file)
        with col1:
            st.image(img, caption="Original Bill", use_container_width=True)

        if st.button("Analyze & Create Professional Excel ✨"):
            with st.spinner("AI Analysis kar raha hai..."):
                try:
                    model = genai.GenerativeModel('gemini-2.5-flash')
                    
                    # SAKHT PROMPT: Isse Excel perfect aayegi
                    prompt = """Analyze this invoice image very carefully:
                    1. Extract Shop Name.
                    2. Create a Markdown Table with columns: S.No | Description | HSN | Qty | Rate | GST % | Amount
                    3. After items, MUST add rows for: Subtotal, CGST, SGST, Round Off, and GRAND TOTAL.
                    Final Line must be: DATA: [Shop Name] | [Total Amount]"""

                    response = model.generate_content([prompt, img])
                    res_text = response.text
                    
                    # Store in Session
                    st.session_state.analysis_result = res_text
                    
                    # Extract Summary Data
                    if "DATA:" in res_text:
                        raw = res_text.split("DATA:")[1].strip()
                        st.session_state.shop_name = raw.split("|")[0].strip()
                        st.session_state.grand_total = raw.split("|")[1].strip()
                    
                    st.rerun()
                except Exception as e:
                    st.error(f"AI Error: {e}")

    # --- 4. EXCEL GENERATION AREA ---
    if 'analysis_result' in st.session_state:
        with col2:
            st.success("Analysis Done!")
            st.markdown(st.session_state.analysis_result)
            
            try:
                # Table nikalna
                table_rows = re.findall(r'\|(.+)\|', st.session_state.analysis_result)
                if len(table_rows) > 1:
                    data = []
                    for r in table_rows:
                        if "---" not in r:
                            cols = [c.strip().replace('**', '').replace('"', '') for c in r.split('|')]
                            cols = [c for c in cols if c != ""]
                            if cols: data.append(cols)
                    
                    df = pd.DataFrame(data[1:], columns=data[0])

                    # Excel taiyar karna
                    output = io.BytesIO()
                    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
                        df.to_excel(writer, index=False, sheet_name='GST_Report', startrow=4)
                        
                        workbook  = writer.book
                        worksheet = writer.sheets['GST_Report']
                        
                        # Style: Blue Header
                        header_fmt = workbook.add_format({'bold': True, 'bg_color': '#1F4E78', 'font_color': 'white', 'border': 1})
                        # Style: Title
                        title_fmt = workbook.add_format({'bold': True, 'font_size': 16, 'font_color': '#1F4E78'})

                        # Header likhna
                        worksheet.write('A1', f"BUSINESS REPORT: {st.session_state.get('shop_name', 'N/A')}", title_fmt)
                        worksheet.write('A2', f"DATE: {datetime.now().strftime('%d-%m-%Y')}")
                        worksheet.write('A3', f"GENERATED BY: AI DIGITAL ACCOUNTANT")

                        # Table formatting
                        for col_num, value in enumerate(df.columns.values):
                            worksheet.write(4, col_num, value, header_fmt)
                            worksheet.set_column(col_num, col_num, 20)

                    st.download_button(
                        label="📥 Download Full GST Excel Report",
                        data=output.getvalue(),
                        file_name=f"Report_{datetime.now().strftime('%H%M%S')}.xlsx",
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    )
            except Exception as e:
                st.error(f"Excel Formatting Error: {e}")