import streamlit as st
import google.generativeai as genai
import pandas as pd
from PIL import Image
import gspread
from google.oauth2.service_account import Credentials
from io import BytesIO
import json
from datetime import datetime

# --- CONFIG & UI ---
st.set_page_config(page_title="DataSnap AI Agent", layout="wide")
st.markdown("<style>.stApp{background:#0b0e14;color:white;}</style>", unsafe_allow_html=True)

# --- LOGIN ---
if 'login' not in st.session_state: st.session_state['login'] = False
if not st.session_state['login']:
    st.title("🔐 AI Agent Portal")
    p = st.text_input("Access Key", type="password")
    if st.button("Unlock"):
        if p == st.secrets["ADMIN_PASSWORD"]: 
            st.session_state['login'] = True
            st.rerun()
    st.stop()

# --- AGENT SETUP ---
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
try:
    all_m = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    model = genai.GenerativeModel('models/gemini-1.5-flash' if 'models/gemini-1.5-flash' in all_m else all_m[0])
except: st.error("AI Error")

# --- AGENT BRAIN (The Logic) ---
def process_with_ai_agent(image):
    today = datetime.now().strftime("%d-%m-%Y")
    # Yahan hum AI ko Agent bana rahe hain
    agent_instruction = f"""
    You are an AI Digital Accountant. Analyze this invoice image.
    1. Extract Header: Vendor Name and Date.
    2. Extract Table: S.No, Description, HSN, Qty, Rate, GST %, Amount.
    3. Mathematical Check: Calculate Subtotal, CGST (9%), SGST (9%), and Grand Total.
    4. If Round Off is needed, calculate it.
    
    OUTPUT FORMAT: Return a JSON list of lists exactly like this:
    [
        ["BUSINESS REPORT: [Vendor Name]", "", "", "", "", "", ""],
        ["DATE: {today}", "", "", "", "", "", ""],
        ["GENERATED BY: AI DIGITAL ACCOUNTANT", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["S.No", "Description", "HSN", "Qty", "Rate", "GST %", "Amount"],
        ["1", "Item Name", "HSN Code", "1", "100", "18%", "118"],
        ["Subtotal", "Calculation", "", "", "", "", "TotalValue"],
        ["CGST", "9%", "", "", "", "", "TaxValue"],
        ["SGST", "9%", "", "", "", "", "TaxValue"],
        ["GRAND TOTAL", "FinalValue", "", "", "", "", "FinalValue"]
    ]
    """
    response = model.generate_content([agent_instruction, image])
    return response.text

# --- APP MAIN ---
st.title("🤖 DataSnap AI ")
st.write("upload any image,your excel file is ready.")

up = st.file_uploader("Upload Invoice", type=['jpg','png','jpeg'])

if up:
    img = Image.open(up)
    st.image(img, width=400)
    if st.button("🚀 Agent Analysis Start"):
        with st.spinner("AI Agent is calculating taxes..."):
            raw_res = process_with_ai_agent(img)
            try:
                # Clean and Load JSON
                clean_json = raw_res.replace("```json","").replace("```","").strip()
                data = json.loads(clean_json)
                df = pd.DataFrame(data)
                
                st.subheader("📋 Professional Report Preview")
                st.dataframe(df, use_container_width=True)
                
                # Excel Build
                out = BytesIO()
                with pd.ExcelWriter(out, engine='xlsxwriter') as wr:
                    df.to_excel(wr, index=False, header=False, sheet_name='GST_Report')
                
                st.download_button("📥 Download GST Excel Report", out.getvalue(), "AI_GST_Report.xlsx")
                
                # Sheet Sync
                # (Make sure to add your sync function here)
                st.success("Analysis Complete! Professional Report Ready.")
            except:
                st.error("AI Agent confusion mein hai. Photo saaf khinche.")
                st.write(raw_res)

# --- PLANS ---
st.sidebar.title("💎 Business Plans")
st.sidebar.info("₹200 - 20 Scans\n₹1200 - Unlimited\n₹5000 - Enterprise")